./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/tomekkorbak/oura-mcp-server
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/tosin2013/mcp-codebase-insight
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/trafflux/pdf-reader-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/truaxki/mcp-Pdf2png
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/tsmztech/mcp-server-salesforce
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/ttjslbz001/akshare_mcp_server
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/tuanle96/mcp-odoo
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/tulong66/mcp-tavily-proxy
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/tuskermanshu/swagger-mcp-server
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/tylerstoltz/mcp-odbc
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/tywenk/mcp-sol
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/v4lheru/trello-mcp-server
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/valyu-network/valyu-mcp-js
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/vectorize-io/vectorize-mcp-server
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/vinayak-mehta/gmail-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/vincentf305/mcp-server-deepseek
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/vivalalova/mcp_practice
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/vlttnv/k8s-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/vurtnec/mcp-LanceDB-node
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/w-jeon/mcp-brave-search
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/waifuai/mcp-waifu-queue
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/wazzan/mcp-coincap-jj
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/westsideori/cursor-a11y-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/wllcnm/dingding-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/wonderwhy-er/DesktopCommanderMCP
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/wowyuarm/file-converter-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/wrale/mcp-server-tree-sitter
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/wysh3/perplexity-mcp-zerver
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/xiangma9712/mysql-mcp-server
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/xindong888999/phalcon-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/xiyuefox/mcp-hfspace
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/xpn/mythic_mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/xraywu/mcp-wegene-assistant
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/xxxbrian/mcp-rquest
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/yangkyeongmo/mcp-server-openmetadata
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/yanmxa/multicluster-mcp-server
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/yctimlin/mcp_excalidraw
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/yhc984/cursor-talk-to-figma-mcp-main
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/ynu/mcp-ynu
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/yoavniran/cloudinary-mcp-server
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/yodakeisuke/mcp-memory-domain-knowledge
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/yokingma/one-search-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/yuru-sha/mcp-server-dify
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/yuru-sha/mcp-server-mysql
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/zajTools/zaj-MySQL-MCP
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/zanetworker/mcp-docling
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/zannyonear1h1/mcp-memory-bank-1
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/zekus/shortcut-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/zereight/confluence-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/zereight/gitlab-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/zhangzhongnan928/mcp-pa-ai-agent
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/zhiwei5576/excel-mcp-server
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/zoharbabin/kaltura-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/zqushair/Frontapp-MCP
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/ztobs/cline-browser-use-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/zueai/neon-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/zueai/workos-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/zxfgds/mcp-code-indexer
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/zym9863/pixabay-mcp
./MCP-Mirror/utils/mirror-github-repos-to-MCP-Mirror.sh --directory /Users/kurt/GitHub/MCP-Mirror --repo https://github.com/zym9863/together-ai-image-server
